#!/bin/bash
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
AOSP_ROOT="${1:?usage: INSTALL_AOSP.sh /path/to/aosp}"
DEST="$AOSP_ROOT/hardware/interfaces/audio/aidl/default/eqsb"
mkdir -p "$DEST/dsp" "$DEST/eq" "$DEST/dynamics" "$DEST/effects"
cp "$HERE/EQsbEffect.h" "$HERE/EQsbEffect.cpp" "$DEST/"
cp "$HERE/Android.bp" "$DEST/"
cp "$HERE/audio_effects_config_eqsb.xml" "$DEST/"
cp "$HERE/merge_audio_effects_config.py" "$DEST/"
cp "$HERE/PLATFORM_INTEGRATION.md" "$DEST/"
cp "$HERE/eqsb_product.mk" "$DEST/"
cp "$HERE"/../../../app/src/main/cpp/EQsbDspEngine.{h,cpp} "$DEST/"
cp "$HERE"/../../../app/src/main/cpp/dsp/BiquadFilter.{h,cpp} "$DEST/dsp/"
cp "$HERE"/../../../app/src/main/cpp/dsp/DspUtils.h "$DEST/dsp/"
cp "$HERE"/../../../app/src/main/cpp/dsp/{PreGain,MasterGain,Balance}.h "$DEST/dsp/"
cp "$HERE"/../../../app/src/main/cpp/eq/EQ32.{h,cpp} "$DEST/eq/"
cp "$HERE"/../../../app/src/main/cpp/dynamics/{MDRC,AutoGain,Limiter}.{h,cpp} "$DEST/dynamics/"
cp "$HERE"/../../../app/src/main/cpp/effects/{BassBoost,ToneControl,SpatialVirtualizer}.{h,cpp} "$DEST/effects/"
echo "EQsb AIDL effect staged at $DEST"
echo "Next: include $DEST/eqsb_product.mk from the target product makefile (or add libeqsb_aidl_effect to PRODUCT_PACKAGES)."
echo "Merge $DEST/audio_effects_config_eqsb.xml into the device active audio_effects_config.xml using $DEST/merge_audio_effects_config.py; do not replace the OEM config."
echo "Build and flash the target vendor image. Staging source files alone does not register the effect on a running device."
